### ISSUE TITLE
Screen

### ISSUE THREAD

**Issue by t-davidson** [socdyn/wiki#1]
Let's add a short tutorial to using screen, which is pretty essential to many tasks on Vesta.

**Comment by georgeberry** [comment]
Assigned to @mariomolinam

**Comment by chrisjcameron** [comment]
If you search your email, I am sure I included a small description of screen. You should also move  some of the information from confluence.

**Comment by mariomolinam** [comment]
Ok, I got this. I'll write a brief description on how using screen tomorrow morning.

**Comment by chrisjcameron** [comment]
I posted my old intro. You can work from there. 

On September 12, 2016, at 10:26 PM, Mario Molina <notifications@github.com> wrote:

Ok, I got this. I'll write a brief description on how using screen tomorrow morning.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/socdyn/wiki","title":"socdyn/wiki","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/socdyn/wiki">https://github.com/socdyn/wiki</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mariomolinam in #1: Ok, I got this. I'll write a brief description on how using screen tomorrow morning."}],"action":{"name":"View Issue","url":"<a href="https://github.com/socdyn/wiki/issues/1#issuecomment-246554937">https://github.com/socdyn/wiki/issues/1#issuecomment-246554937</a>"}}}

**Comment by t-davidson** [comment]
I saw Chris' commit and updated the tutorial with some info I had provided my MPS students. It should now more clearly reflect the actual usage of the screen.

**Comment by t-davidson** [comment]
Closed the issue since Chris, Mario, & I all added additional detail
